---
- hosts: webserver
  become: yes

  vars_files:
    - vars.yml

  tasks:
    - name: "Ensure the User '{{ user_name }}' is present and their Home Directory setup"
      ansible.builtin.user:
        name: "{{ user_name }}"
        # TODO
        # password: "{{ user_password }}"
        shell: /bin/bash
        groups: sudo,www-data
        append: yes
        create_home: yes
        home: "/home/{{ user_name }}"

    - name: Set authorized key taken from file
      ansible.posix.authorized_key:
        user: "{{ user_name }}"
        state: present
        key: "{{ lookup('file', 'public_keys/craft_worker.pub') }}"
