- name: Ensure the Default Site directory Exists
  ansible.builtin.file:
    path: "/home/{{ craft_user_name }}/default"
    state: directory
    owner: "{{ craft_user_name }}"
    group: "{{ craft_user_name }}"
    mode: '0775'
    recurse: yes        

- name: Ensure the Default Site Exists
  ansible.builtin.template:
    src: caddy/default/index.html
    dest: "/home/{{ craft_user_name }}/default/index.html"
    owner: www-data
    group: root
    mode: '0755'

- name: Ensure the Default Site is Available
  vars:
    hostname: "{{inventory_hostname}}"
    site_path: "/home/{{ craft_user_name }}/default"
  ansible.builtin.template:
    src: caddy/Site.j2
    dest: "/etc/caddy/sites-available/default"
    owner: root
    group: root
    mode: '0664'

- name: Ensure the Default Site is Enabled
  notify: 
    - Reload caddy
  ansible.builtin.file:
    src: /etc/caddy/sites-available/default
    dest: /etc/caddy/sites-enabled/default
    owner: root
    group: root
    state: link