caddy_config: "{{ lookup('template', 'caddy/Caddyfile.j2') }}"
caddy_update: false
# This allows Caddy to open a low port (under 1024 - e.g. 80, 443).
caddy_systemd_capabilities_enabled: true
caddy_systemd_capabilities: "CAP_NET_BIND_SERVICE"
caddy_systemd_restart: 20